apiVersion: v1
kind: Service
metadata:
  labels:
    app: wikistats-consumer
  name: wikistats-consumer
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 2112
      targetPort: 2112
  selector:
    app: wikistats-consumer
