// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/database.proto

package database

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsUpdateMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	IsBot         bool                   `protobuf:"varint,4,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsUpdateMsg) Reset() {
	*x = StatsUpdateMsg{}
	mi := &file_api_proto_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsUpdateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsUpdateMsg) ProtoMessage() {}

func (x *StatsUpdateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsUpdateMsg.ProtoReflect.Descriptor instead.
func (*StatsUpdateMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_database_proto_rawDescGZIP(), []int{0}
}

func (x *StatsUpdateMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatsUpdateMsg) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StatsUpdateMsg) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *StatsUpdateMsg) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

type UpdateDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatsUpdate   []*StatsUpdateMsg      `protobuf:"bytes,1,rep,name=stats_update,json=statsUpdate,proto3" json:"stats_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatabaseRequest) Reset() {
	*x = UpdateDatabaseRequest{}
	mi := &file_api_proto_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatabaseRequest) ProtoMessage() {}

func (x *UpdateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*UpdateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDatabaseRequest) GetStatsUpdate() []*StatsUpdateMsg {
	if x != nil {
		return x.StatsUpdate
	}
	return nil
}

type UpdateDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatabaseResponse) Reset() {
	*x = UpdateDatabaseResponse{}
	mi := &file_api_proto_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatabaseResponse) ProtoMessage() {}

func (x *UpdateDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatabaseResponse.ProtoReflect.Descriptor instead.
func (*UpdateDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_database_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDatabaseResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_proto_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_proto_rawDescGZIP(), []int{3}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      int64                  `protobuf:"varint,1,opt,name=messages,proto3" json:"messages,omitempty"`
	Users         int64                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	Bots          int64                  `protobuf:"varint,3,opt,name=bots,proto3" json:"bots,omitempty"`
	Servers       int64                  `protobuf:"varint,4,opt,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_proto_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_database_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsResponse) GetMessages() int64 {
	if x != nil {
		return x.Messages
	}
	return 0
}

func (x *GetStatsResponse) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *GetStatsResponse) GetBots() int64 {
	if x != nil {
		return x.Bots
	}
	return 0
}

func (x *GetStatsResponse) GetServers() int64 {
	if x != nil {
		return x.Servers
	}
	return 0
}

type ValidateLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateLoginRequest) Reset() {
	*x = ValidateLoginRequest{}
	mi := &file_api_proto_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateLoginRequest) ProtoMessage() {}

func (x *ValidateLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateLoginRequest.ProtoReflect.Descriptor instead.
func (*ValidateLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValidateLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ValidateLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateLoginResponse) Reset() {
	*x = ValidateLoginResponse{}
	mi := &file_api_proto_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateLoginResponse) ProtoMessage() {}

func (x *ValidateLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateLoginResponse.ProtoReflect.Descriptor instead.
func (*ValidateLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_database_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateLoginResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_api_proto_database_proto protoreflect.FileDescriptor

const file_api_proto_database_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/database.proto\x12\bdatabase\"c\n" +
	"\x0eStatsUpdateMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12\x15\n" +
	"\x06is_bot\x18\x04 \x01(\bR\x05isBot\"T\n" +
	"\x15UpdateDatabaseRequest\x12;\n" +
	"\fstats_update\x18\x01 \x03(\v2\x18.database.StatsUpdateMsgR\vstatsUpdate\".\n" +
	"\x16UpdateDatabaseResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x11\n" +
	"\x0fGetStatsRequest\"r\n" +
	"\x10GetStatsResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x01(\x03R\bmessages\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x03R\x05users\x12\x12\n" +
	"\x04bots\x18\x03 \x01(\x03R\x04bots\x12\x18\n" +
	"\aservers\x18\x04 \x01(\x03R\aservers\"N\n" +
	"\x14ValidateLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"-\n" +
	"\x15ValidateLoginResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2\xf6\x01\n" +
	"\n" +
	"Repository\x12S\n" +
	"\x0eUpdateDatabase\x12\x1f.database.UpdateDatabaseRequest\x1a .database.UpdateDatabaseResponse\x12A\n" +
	"\bGetStats\x12\x19.database.GetStatsRequest\x1a\x1a.database.GetStatsResponse\x12P\n" +
	"\rValidateLogin\x12\x1e.database.ValidateLoginRequest\x1a\x1f.database.ValidateLoginResponseB2Z0github.com/lauchlant/wikistats/internal/databaseb\x06proto3"

var (
	file_api_proto_database_proto_rawDescOnce sync.Once
	file_api_proto_database_proto_rawDescData []byte
)

func file_api_proto_database_proto_rawDescGZIP() []byte {
	file_api_proto_database_proto_rawDescOnce.Do(func() {
		file_api_proto_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_database_proto_rawDesc), len(file_api_proto_database_proto_rawDesc)))
	})
	return file_api_proto_database_proto_rawDescData
}

var file_api_proto_database_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_database_proto_goTypes = []any{
	(*StatsUpdateMsg)(nil),         // 0: database.StatsUpdateMsg
	(*UpdateDatabaseRequest)(nil),  // 1: database.UpdateDatabaseRequest
	(*UpdateDatabaseResponse)(nil), // 2: database.UpdateDatabaseResponse
	(*GetStatsRequest)(nil),        // 3: database.GetStatsRequest
	(*GetStatsResponse)(nil),       // 4: database.GetStatsResponse
	(*ValidateLoginRequest)(nil),   // 5: database.ValidateLoginRequest
	(*ValidateLoginResponse)(nil),  // 6: database.ValidateLoginResponse
}
var file_api_proto_database_proto_depIdxs = []int32{
	0, // 0: database.UpdateDatabaseRequest.stats_update:type_name -> database.StatsUpdateMsg
	1, // 1: database.Repository.UpdateDatabase:input_type -> database.UpdateDatabaseRequest
	3, // 2: database.Repository.GetStats:input_type -> database.GetStatsRequest
	5, // 3: database.Repository.ValidateLogin:input_type -> database.ValidateLoginRequest
	2, // 4: database.Repository.UpdateDatabase:output_type -> database.UpdateDatabaseResponse
	4, // 5: database.Repository.GetStats:output_type -> database.GetStatsResponse
	6, // 6: database.Repository.ValidateLogin:output_type -> database.ValidateLoginResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_database_proto_init() }
func file_api_proto_database_proto_init() {
	if File_api_proto_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_database_proto_rawDesc), len(file_api_proto_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_database_proto_goTypes,
		DependencyIndexes: file_api_proto_database_proto_depIdxs,
		MessageInfos:      file_api_proto_database_proto_msgTypes,
	}.Build()
	File_api_proto_database_proto = out.File
	file_api_proto_database_proto_goTypes = nil
	file_api_proto_database_proto_depIdxs = nil
}
