{
 "title": "Wikistats Dashboard",
 "description": "Stats for the Wikistats application",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Events Processed",
   "type": "timeseries",
   "description": "Number of events successfully processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(consumer_events_processed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Events",
   "type": "timeseries",
   "description": "Number of events that failed to process",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(consumer_events_failed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Producer Events Persisted",
   "type": "timeseries",
   "description": "Number of events persisted to Redpanda",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(producer_events_persisted)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumer Events Consumed",
   "type": "timeseries",
   "description": "Number of events consumed from Redpanda",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(consumer_events_consumed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Producer Events Consumed",
   "type": "timeseries",
   "description": "Number of events consumed from the Wikimedia recent changes stream",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum(producer_events_consumed)", "legendFormat": "__auto" }
   ]
  }
 ]
}