apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
    - name: rpc
      port: 33145