apiVersion: v1
data:
  grafana_provider.yml: |-
    apiVersion: 1

    providers:
      - name: 'Wikistats Dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: grafana
  name: grafana-cm1
