apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ../../../kompose convert -f docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: wikistats-api
  name: wikistats-api
spec:
  containers:
    - image: ghcr.io/lauchlant/wikistats/ch-9-api:latest
      name: wikistats-api
      ports:
        - containerPort: 7000
          protocol: TCP
      securityContext:
        readOnlyRootFilesystem: true
        runAsGroup: 1000
        runAsUser: 1000
  hostname: api
  restartPolicy: OnFailure
